spring:
  datasource:
    url: jdbc:mysql://localhost:3303/db_tap_rest?useSSL=false&serverTimezone=America/Guayaquil
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: debug
