spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_tap_rest?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Guayaquil
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 

logging:
  level:
    org:
      hibernate:
        SQL: debug
